framework:
  asset_mapper:
    # The paths to make available to the asset mapper.
    paths:
      - assets/
    missing_import_mode: strict
    excluded_patterns:
      - '*/assets/styles/_*.scss'
      - '*/assets/styles/**/_*.scss'
    exclude_dotfiles: true
    # set this option to false to disable the shim entirely
    # (your website/web app won't work in old browsers)
    #importmap_polyfill: false
    importmap_script_attributes:
      crossorigin: 'anonymous'

when@prod:
  framework:
    asset_mapper:
      missing_import_mode: warn
