<?php

namespace tests\Controller;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

class GithubWebhookTest extends WebTestCase
{
	private KernelBrowser $kernelBrowser;

	private function initServices(): void
	{
		$this->kernelBrowser = self::createClient();
	}

	public function testWebhook(): void
	{
		$this->initServices();

		$i = 0;
		while (true) {
			$payload = match (++$i) {
				1 => $this->getPingPayload(),
				2 => $this->getIssueAssignedPayload(),
				3 => $this->getIssueOpenPayload(),
				4 => $this->getIssueClosedPayload(),
				default => null,
			};
			if (null === $payload) {
				break;
			}
			$this->assertPayload($payload);
		}
	}

	private function assertPayload(array $payload): void
	{
		$this->kernelBrowser->request('POST', '/webhook/github', [], [], [], json_encode($payload));

		$statusCode = $this->kernelBrowser->getResponse()->getStatusCode();
		$this->assertEquals(Response::HTTP_ACCEPTED, $statusCode);
	}

	private function getIssueAssignedPayload(): array
	{
		return [
			'action' => 'assigned',
			'issue' => [
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5',
				'repository_url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/labels{/name}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/comments',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/events',
				'html_url' => 'https://github.com/marsender/symfony-webhook/issues/5',
				'id' => 2206273214,
				'node_id' => 'I_kwDOLk3wls6DgQ6-',
				'number' => 5,
				'title' => 'Add code coverage and badge',
				'user' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'labels' => [],
				'state' => 'open',
				'locked' => false,
				'assignee' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'assignees' => [
					[
						'login' => 'marsender',
						'id' => 279979,
						'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
						'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
						'gravatar_id' => '',
						'url' => 'https://api.github.com/users/marsender',
						'html_url' => 'https://github.com/marsender',
						'followers_url' => 'https://api.github.com/users/marsender/followers',
						'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
						'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
						'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
						'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
						'organizations_url' => 'https://api.github.com/users/marsender/orgs',
						'repos_url' => 'https://api.github.com/users/marsender/repos',
						'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
						'received_events_url' => 'https://api.github.com/users/marsender/received_events',
						'type' => 'User',
						'site_admin' => false,
					],
				],
				'milestone' => null,
				'comments' => 0,
				'created_at' => '2024-03-25T17:11:54Z',
				'updated_at' => '2024-03-25T17:11:54Z',
				'closed_at' => null,
				'author_association' => 'OWNER',
				'active_lock_reason' => null,
				'body' => null,
				'reactions' => [
					'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/reactions',
					'total_count' => 0,
					'+1' => 0,
					0,
					'laugh' => 0,
					'hooray' => 0,
					'confused' => 0,
					'heart' => 0,
					'rocket' => 0,
					'eyes' => 0,
				],
				'timeline_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/timeline',
				'performed_via_github_app' => null,
				'state_reason' => null,
			],
			'assignee' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
			'repository' => [
				'id' => 776859798,
				'node_id' => 'R_kgDOLk3wlg',
				'name' => 'symfony-webhook',
				'full_name' => 'marsender/symfony-webhook',
				'private' => true,
				'owner' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'html_url' => 'https://github.com/marsender/symfony-webhook',
				'description' => null,
				'fork' => false,
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'forks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/forks',
				'keys_url' => 'https://api.github.com/repos/marsender/symfony-webhook/keys{/key_id}',
				'collaborators_url' => 'https://api.github.com/repos/marsender/symfony-webhook/collaborators{/collaborator}',
				'teams_url' => 'https://api.github.com/repos/marsender/symfony-webhook/teams',
				'hooks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/hooks',
				'issue_events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/events{/number}',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/events',
				'assignees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/assignees{/user}',
				'branches_url' => 'https://api.github.com/repos/marsender/symfony-webhook/branches{/branch}',
				'tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/tags',
				'blobs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/blobs{/sha}',
				'git_tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/tags{/sha}',
				'git_refs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/refs{/sha}',
				'trees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/trees{/sha}',
				'statuses_url' => 'https://api.github.com/repos/marsender/symfony-webhook/statuses/{sha}',
				'languages_url' => 'https://api.github.com/repos/marsender/symfony-webhook/languages',
				'stargazers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/stargazers',
				'contributors_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contributors',
				'subscribers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscribers',
				'subscription_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscription',
				'commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/commits{/sha}',
				'git_commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/commits{/sha}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/comments{/number}',
				'issue_comment_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/comments{/number}',
				'contents_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contents/{+path}',
				'compare_url' => 'https://api.github.com/repos/marsender/symfony-webhook/compare/{base}...{head}',
				'merges_url' => 'https://api.github.com/repos/marsender/symfony-webhook/merges',
				'archive_url' => 'https://api.github.com/repos/marsender/symfony-webhook/{archive_format}{/ref}',
				'downloads_url' => 'https://api.github.com/repos/marsender/symfony-webhook/downloads',
				'issues_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues{/number}',
				'pulls_url' => 'https://api.github.com/repos/marsender/symfony-webhook/pulls{/number}',
				'milestones_url' => 'https://api.github.com/repos/marsender/symfony-webhook/milestones{/number}',
				'notifications_url' => 'https://api.github.com/repos/marsender/symfony-webhook/notifications{?since,all,participating}',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/labels{/name}',
				'releases_url' => 'https://api.github.com/repos/marsender/symfony-webhook/releases{/id}',
				'deployments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/deployments',
				'created_at' => '2024-03-24T16:40:06Z',
				'updated_at' => '2024-03-24T16:59:34Z',
				'pushed_at' => '2024-03-25T17:12:30Z',
				'git_url' => 'git://github.com/marsender/symfony-webhook.git',
				'ssh_url' => 'git@github.com:marsender/symfony-webhook.git',
				'clone_url' => 'https://github.com/marsender/symfony-webhook.git',
				'svn_url' => 'https://github.com/marsender/symfony-webhook',
				'homepage' => null,
				'size' => 220,
				'stargazers_count' => 0,
				'watchers_count' => 0,
				'language' => 'PHP',
				'has_issues' => true,
				'has_projects' => true,
				'has_downloads' => true,
				'has_wiki' => false,
				'has_pages' => false,
				'has_discussions' => false,
				'forks_count' => 0,
				'mirror_url' => null,
				'archived' => false,
				'disabled' => false,
				'open_issues_count' => 2,
				'license' => null,
				'allow_forking' => true,
				'is_template' => false,
				'web_commit_signoff_required' => false,
				'topics' => [],
				'visibility' => 'private',
				'forks' => 0,
				'open_issues' => 2,
				'watchers' => 0,
				'default_branch' => 'main',
			],
			'sender' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
		];
	}

	private function getIssueOpenPayload(): array
	{
		return json_decode('
		{
			"action": "opened",
			"issue": {
				"url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283",
				"repository_url": "https://api.github.com/repos/Alveos/easylibrary_back",
				"labels_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283/labels{/name}",
				"comments_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283/comments",
				"events_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283/events",
				"html_url": "https://github.com/Alveos/easylibrary_back/issues/283",
				"id": 2219096421,
				"node_id": "I_kwDOFI1cXs6ERLll",
				"number": 283,
				"title": "Webhook test issue for easylibrary",
				"user": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"labels": [
		
				],
				"state": "open",
				"locked": false,
				"assignee": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"assignees": [
					{
						"login": "marsender",
						"id": 279979,
						"node_id": "MDQ6VXNlcjI3OTk3OQ==",
						"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/marsender",
						"html_url": "https://github.com/marsender",
						"followers_url": "https://api.github.com/users/marsender/followers",
						"following_url": "https://api.github.com/users/marsender/following{/other_user}",
						"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
						"organizations_url": "https://api.github.com/users/marsender/orgs",
						"repos_url": "https://api.github.com/users/marsender/repos",
						"events_url": "https://api.github.com/users/marsender/events{/privacy}",
						"received_events_url": "https://api.github.com/users/marsender/received_events",
						"type": "User",
						"site_admin": false
					}
				],
				"milestone": null,
				"comments": 0,
				"created_at": "2024-04-01T21:28:42Z",
				"updated_at": "2024-04-01T21:28:43Z",
				"closed_at": null,
				"author_association": "COLLABORATOR",
				"active_lock_reason": null,
				"body": null,
				"reactions": {
					"url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283/reactions",
					"total_count": 0,
					"+1": 0,
					"-1": 0,
					"laugh": 0,
					"hooray": 0,
					"confused": 0,
					"heart": 0,
					"rocket": 0,
					"eyes": 0
				},
				"timeline_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/283/timeline",
				"performed_via_github_app": null,
				"state_reason": null
			},
			"repository": {
				"id": 344808542,
				"node_id": "MDEwOlJlcG9zaXRvcnkzNDQ4MDg1NDI=",
				"name": "easylibrary_back",
				"full_name": "Alveos/easylibrary_back",
				"private": true,
				"owner": {
					"login": "Alveos",
					"id": 525217,
					"node_id": "MDEyOk9yZ2FuaXphdGlvbjUyNTIxNw==",
					"avatar_url": "https://avatars.githubusercontent.com/u/525217?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/Alveos",
					"html_url": "https://github.com/Alveos",
					"followers_url": "https://api.github.com/users/Alveos/followers",
					"following_url": "https://api.github.com/users/Alveos/following{/other_user}",
					"gists_url": "https://api.github.com/users/Alveos/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/Alveos/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/Alveos/subscriptions",
					"organizations_url": "https://api.github.com/users/Alveos/orgs",
					"repos_url": "https://api.github.com/users/Alveos/repos",
					"events_url": "https://api.github.com/users/Alveos/events{/privacy}",
					"received_events_url": "https://api.github.com/users/Alveos/received_events",
					"type": "Organization",
					"site_admin": false
				},
				"html_url": "https://github.com/Alveos/easylibrary_back",
				"description": null,
				"fork": false,
				"url": "https://api.github.com/repos/Alveos/easylibrary_back",
				"forks_url": "https://api.github.com/repos/Alveos/easylibrary_back/forks",
				"keys_url": "https://api.github.com/repos/Alveos/easylibrary_back/keys{/key_id}",
				"collaborators_url": "https://api.github.com/repos/Alveos/easylibrary_back/collaborators{/collaborator}",
				"teams_url": "https://api.github.com/repos/Alveos/easylibrary_back/teams",
				"hooks_url": "https://api.github.com/repos/Alveos/easylibrary_back/hooks",
				"issue_events_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/events{/number}",
				"events_url": "https://api.github.com/repos/Alveos/easylibrary_back/events",
				"assignees_url": "https://api.github.com/repos/Alveos/easylibrary_back/assignees{/user}",
				"branches_url": "https://api.github.com/repos/Alveos/easylibrary_back/branches{/branch}",
				"tags_url": "https://api.github.com/repos/Alveos/easylibrary_back/tags",
				"blobs_url": "https://api.github.com/repos/Alveos/easylibrary_back/git/blobs{/sha}",
				"git_tags_url": "https://api.github.com/repos/Alveos/easylibrary_back/git/tags{/sha}",
				"git_refs_url": "https://api.github.com/repos/Alveos/easylibrary_back/git/refs{/sha}",
				"trees_url": "https://api.github.com/repos/Alveos/easylibrary_back/git/trees{/sha}",
				"statuses_url": "https://api.github.com/repos/Alveos/easylibrary_back/statuses/{sha}",
				"languages_url": "https://api.github.com/repos/Alveos/easylibrary_back/languages",
				"stargazers_url": "https://api.github.com/repos/Alveos/easylibrary_back/stargazers",
				"contributors_url": "https://api.github.com/repos/Alveos/easylibrary_back/contributors",
				"subscribers_url": "https://api.github.com/repos/Alveos/easylibrary_back/subscribers",
				"subscription_url": "https://api.github.com/repos/Alveos/easylibrary_back/subscription",
				"commits_url": "https://api.github.com/repos/Alveos/easylibrary_back/commits{/sha}",
				"git_commits_url": "https://api.github.com/repos/Alveos/easylibrary_back/git/commits{/sha}",
				"comments_url": "https://api.github.com/repos/Alveos/easylibrary_back/comments{/number}",
				"issue_comment_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues/comments{/number}",
				"contents_url": "https://api.github.com/repos/Alveos/easylibrary_back/contents/{+path}",
				"compare_url": "https://api.github.com/repos/Alveos/easylibrary_back/compare/{base}...{head}",
				"merges_url": "https://api.github.com/repos/Alveos/easylibrary_back/merges",
				"archive_url": "https://api.github.com/repos/Alveos/easylibrary_back/{archive_format}{/ref}",
				"downloads_url": "https://api.github.com/repos/Alveos/easylibrary_back/downloads",
				"issues_url": "https://api.github.com/repos/Alveos/easylibrary_back/issues{/number}",
				"pulls_url": "https://api.github.com/repos/Alveos/easylibrary_back/pulls{/number}",
				"milestones_url": "https://api.github.com/repos/Alveos/easylibrary_back/milestones{/number}",
				"notifications_url": "https://api.github.com/repos/Alveos/easylibrary_back/notifications{?since,all,participating}",
				"labels_url": "https://api.github.com/repos/Alveos/easylibrary_back/labels{/name}",
				"releases_url": "https://api.github.com/repos/Alveos/easylibrary_back/releases{/id}",
				"deployments_url": "https://api.github.com/repos/Alveos/easylibrary_back/deployments",
				"created_at": "2021-03-05T12:45:48Z",
				"updated_at": "2024-03-11T13:59:53Z",
				"pushed_at": "2024-03-29T14:54:00Z",
				"git_url": "git://github.com/Alveos/easylibrary_back.git",
				"ssh_url": "git@github.com:Alveos/easylibrary_back.git",
				"clone_url": "https://github.com/Alveos/easylibrary_back.git",
				"svn_url": "https://github.com/Alveos/easylibrary_back",
				"homepage": null,
				"size": 14808,
				"stargazers_count": 1,
				"watchers_count": 1,
				"language": "PHP",
				"has_issues": true,
				"has_projects": true,
				"has_downloads": true,
				"has_wiki": false,
				"has_pages": false,
				"has_discussions": false,
				"forks_count": 0,
				"mirror_url": null,
				"archived": false,
				"disabled": false,
				"open_issues_count": 1,
				"license": null,
				"allow_forking": false,
				"is_template": false,
				"web_commit_signoff_required": false,
				"topics": [
		
				],
				"visibility": "private",
				"forks": 0,
				"open_issues": 1,
				"watchers": 1,
				"default_branch": "master",
				"custom_properties": {
		
				}
			},
			"organization": {
				"login": "Alveos",
				"id": 525217,
				"node_id": "MDEyOk9yZ2FuaXphdGlvbjUyNTIxNw==",
				"url": "https://api.github.com/orgs/Alveos",
				"repos_url": "https://api.github.com/orgs/Alveos/repos",
				"events_url": "https://api.github.com/orgs/Alveos/events",
				"hooks_url": "https://api.github.com/orgs/Alveos/hooks",
				"issues_url": "https://api.github.com/orgs/Alveos/issues",
				"members_url": "https://api.github.com/orgs/Alveos/members{/member}",
				"public_members_url": "https://api.github.com/orgs/Alveos/public_members{/member}",
				"avatar_url": "https://avatars.githubusercontent.com/u/525217?v=4",
				"description": ""
			},
			"sender": {
				"login": "marsender",
				"id": 279979,
				"node_id": "MDQ6VXNlcjI3OTk3OQ==",
				"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/marsender",
				"html_url": "https://github.com/marsender",
				"followers_url": "https://api.github.com/users/marsender/followers",
				"following_url": "https://api.github.com/users/marsender/following{/other_user}",
				"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
				"organizations_url": "https://api.github.com/users/marsender/orgs",
				"repos_url": "https://api.github.com/users/marsender/repos",
				"events_url": "https://api.github.com/users/marsender/events{/privacy}",
				"received_events_url": "https://api.github.com/users/marsender/received_events",
				"type": "User",
				"site_admin": false
			}
		}
		', true);
	}

	private function getIssueClosedPayload(): array
	{
		return [
			'action' => 'closed',
			'issue' => [
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5',
				'repository_url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/labels{/name}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/comments',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/events',
				'html_url' => 'https://github.com/marsender/symfony-webhook/issues/5',
				'id' => 2206273214,
				'node_id' => 'I_kwDOLk3wls6DgQ6-',
				'number' => 5,
				'title' => 'Add code coverage and badge',
				'user' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'labels' => [],
				'state' => 'closed',
				'locked' => false,
				'assignee' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'assignees' => [
					[
						'login' => 'marsender',
						'id' => 279979,
						'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
						'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
						'gravatar_id' => '',
						'url' => 'https://api.github.com/users/marsender',
						'html_url' => 'https://github.com/marsender',
						'followers_url' => 'https://api.github.com/users/marsender/followers',
						'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
						'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
						'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
						'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
						'organizations_url' => 'https://api.github.com/users/marsender/orgs',
						'repos_url' => 'https://api.github.com/users/marsender/repos',
						'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
						'received_events_url' => 'https://api.github.com/users/marsender/received_events',
						'type' => 'User',
						'site_admin' => false,
					],
				],
				'milestone' => null,
				'comments' => 0,
				'created_at' => '2024-03-25T17:11:54Z',
				'updated_at' => '2024-03-26T06:55:18Z',
				'closed_at' => '2024-03-26T06:55:18Z',
				'author_association' => 'OWNER',
				'active_lock_reason' => null,
				'body' => null,
				'reactions' => [
					'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/reactions',
					'total_count' => 0,
					'+1' => 0,
					0,
					'laugh' => 0,
					'hooray' => 0,
					'confused' => 0,
					'heart' => 0,
					'rocket' => 0,
					'eyes' => 0,
				],
				'timeline_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/timeline',
				'performed_via_github_app' => null,
				'state_reason' => 'completed',
			],
			'repository' => [
				'id' => 776859798,
				'node_id' => 'R_kgDOLk3wlg',
				'name' => 'symfony-webhook',
				'full_name' => 'marsender/symfony-webhook',
				'private' => true,
				'owner' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'html_url' => 'https://github.com/marsender/symfony-webhook',
				'description' => null,
				'fork' => false,
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'forks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/forks',
				'keys_url' => 'https://api.github.com/repos/marsender/symfony-webhook/keys{/key_id}',
				'collaborators_url' => 'https://api.github.com/repos/marsender/symfony-webhook/collaborators{/collaborator}',
				'teams_url' => 'https://api.github.com/repos/marsender/symfony-webhook/teams',
				'hooks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/hooks',
				'issue_events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/events{/number}',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/events',
				'assignees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/assignees{/user}',
				'branches_url' => 'https://api.github.com/repos/marsender/symfony-webhook/branches{/branch}',
				'tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/tags',
				'blobs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/blobs{/sha}',
				'git_tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/tags{/sha}',
				'git_refs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/refs{/sha}',
				'trees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/trees{/sha}',
				'statuses_url' => 'https://api.github.com/repos/marsender/symfony-webhook/statuses/{sha}',
				'languages_url' => 'https://api.github.com/repos/marsender/symfony-webhook/languages',
				'stargazers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/stargazers',
				'contributors_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contributors',
				'subscribers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscribers',
				'subscription_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscription',
				'commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/commits{/sha}',
				'git_commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/commits{/sha}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/comments{/number}',
				'issue_comment_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/comments{/number}',
				'contents_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contents/{+path}',
				'compare_url' => 'https://api.github.com/repos/marsender/symfony-webhook/compare/{base}...{head}',
				'merges_url' => 'https://api.github.com/repos/marsender/symfony-webhook/merges',
				'archive_url' => 'https://api.github.com/repos/marsender/symfony-webhook/{archive_format}{/ref}',
				'downloads_url' => 'https://api.github.com/repos/marsender/symfony-webhook/downloads',
				'issues_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues{/number}',
				'pulls_url' => 'https://api.github.com/repos/marsender/symfony-webhook/pulls{/number}',
				'milestones_url' => 'https://api.github.com/repos/marsender/symfony-webhook/milestones{/number}',
				'notifications_url' => 'https://api.github.com/repos/marsender/symfony-webhook/notifications{?since,all,participating}',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/labels{/name}',
				'releases_url' => 'https://api.github.com/repos/marsender/symfony-webhook/releases{/id}',
				'deployments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/deployments',
				'created_at' => '2024-03-24T16:40:06Z',
				'updated_at' => '2024-03-24T16:59:34Z',
				'pushed_at' => '2024-03-26T06:31:02Z',
				'git_url' => 'git://github.com/marsender/symfony-webhook.git',
				'ssh_url' => 'git@github.com:marsender/symfony-webhook.git',
				'clone_url' => 'https://github.com/marsender/symfony-webhook.git',
				'svn_url' => 'https://github.com/marsender/symfony-webhook',
				'homepage' => null,
				'size' => 271,
				'stargazers_count' => 0,
				'watchers_count' => 0,
				'language' => 'PHP',
				'has_issues' => true,
				'has_projects' => true,
				'has_downloads' => true,
				'has_wiki' => false,
				'has_pages' => false,
				'has_discussions' => false,
				'forks_count' => 0,
				'mirror_url' => null,
				'archived' => false,
				'disabled' => false,
				'open_issues_count' => 1,
				'license' => null,
				'allow_forking' => true,
				'is_template' => false,
				'web_commit_signoff_required' => false,
				'topics' => [],
				'visibility' => 'private',
				'forks' => 0,
				'open_issues' => 1,
				'watchers' => 0,
				'default_branch' => 'main',
			],
			'sender' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
		];
	}

	private function getPingPayload(): array
	{
		return json_decode('
    {
      "zen": "Keep it logically awesome.",
      "hook_id": 470086609,
      "hook": {
        "type": "Repository",
        "id": 470086609,
        "name": "web",
        "active": true,
        "events": [
          "issues"
        ],
        "config": {
          "content_type": "json",
          "insecure_ssl": "0",
          "url": "https://webhook.host/webhook/github"
        },
        "updated_at": "2024-04-01T21:27:42Z",
        "created_at": "2024-04-01T21:27:42Z",
        "url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609",
        "test_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/test",
        "ping_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/pings",
        "deliveries_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/deliveries",
        "last_response": {
          "code": null,
          "status": "unused",
          "message": null
        }
      },
      "repository": {
        "id": 770981096,
        "node_id": "R_kgDOLfQ86A",
        "name": "symfony-assetmapper",
        "full_name": "marsender/symfony-assetmapper",
        "private": false,
        "owner": {
          "login": "marsender",
          "id": 279979,
          "node_id": "MDQ6VXNlcjI3OTk3OQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/marsender",
          "html_url": "https://github.com/marsender",
          "followers_url": "https://api.github.com/users/marsender/followers",
          "following_url": "https://api.github.com/users/marsender/following{/other_user}",
          "gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
          "organizations_url": "https://api.github.com/users/marsender/orgs",
          "repos_url": "https://api.github.com/users/marsender/repos",
          "events_url": "https://api.github.com/users/marsender/events{/privacy}",
          "received_events_url": "https://api.github.com/users/marsender/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/marsender/symfony-assetmapper",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/marsender/symfony-assetmapper",
        "forks_url": "https://api.github.com/repos/marsender/symfony-assetmapper/forks",
        "keys_url": "https://api.github.com/repos/marsender/symfony-assetmapper/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/marsender/symfony-assetmapper/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/marsender/symfony-assetmapper/teams",
        "hooks_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks",
        "issue_events_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues/events{/number}",
        "events_url": "https://api.github.com/repos/marsender/symfony-assetmapper/events",
        "assignees_url": "https://api.github.com/repos/marsender/symfony-assetmapper/assignees{/user}",
        "branches_url": "https://api.github.com/repos/marsender/symfony-assetmapper/branches{/branch}",
        "tags_url": "https://api.github.com/repos/marsender/symfony-assetmapper/tags",
        "blobs_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/marsender/symfony-assetmapper/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/marsender/symfony-assetmapper/languages",
        "stargazers_url": "https://api.github.com/repos/marsender/symfony-assetmapper/stargazers",
        "contributors_url": "https://api.github.com/repos/marsender/symfony-assetmapper/contributors",
        "subscribers_url": "https://api.github.com/repos/marsender/symfony-assetmapper/subscribers",
        "subscription_url": "https://api.github.com/repos/marsender/symfony-assetmapper/subscription",
        "commits_url": "https://api.github.com/repos/marsender/symfony-assetmapper/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/marsender/symfony-assetmapper/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/marsender/symfony-assetmapper/contents/{+path}",
        "compare_url": "https://api.github.com/repos/marsender/symfony-assetmapper/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/marsender/symfony-assetmapper/merges",
        "archive_url": "https://api.github.com/repos/marsender/symfony-assetmapper/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/marsender/symfony-assetmapper/downloads",
        "issues_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues{/number}",
        "pulls_url": "https://api.github.com/repos/marsender/symfony-assetmapper/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/marsender/symfony-assetmapper/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/marsender/symfony-assetmapper/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/marsender/symfony-assetmapper/labels{/name}",
        "releases_url": "https://api.github.com/repos/marsender/symfony-assetmapper/releases{/id}",
        "deployments_url": "https://api.github.com/repos/marsender/symfony-assetmapper/deployments",
        "created_at": "2024-03-12T13:35:23Z",
        "updated_at": "2024-03-20T20:46:10Z",
        "pushed_at": "2024-03-29T17:24:02Z",
        "git_url": "git://github.com/marsender/symfony-assetmapper.git",
        "ssh_url": "git@github.com:marsender/symfony-assetmapper.git",
        "clone_url": "https://github.com/marsender/symfony-assetmapper.git",
        "svn_url": "https://github.com/marsender/symfony-assetmapper",
        "homepage": null,
        "size": 405,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "PHP",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
      },
      "sender": {
        "login": "marsender",
        "id": 279979,
        "node_id": "MDQ6VXNlcjI3OTk3OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/marsender",
        "html_url": "https://github.com/marsender",
        "followers_url": "https://api.github.com/users/marsender/followers",
        "following_url": "https://api.github.com/users/marsender/following{/other_user}",
        "gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
        "organizations_url": "https://api.github.com/users/marsender/orgs",
        "repos_url": "https://api.github.com/users/marsender/repos",
        "events_url": "https://api.github.com/users/marsender/events{/privacy}",
        "received_events_url": "https://api.github.com/users/marsender/received_events",
        "type": "User",
        "site_admin": false
      }
    }
		', true);
	}
}
