<?php

namespace tests\Controller;

use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;
use Symfony\Component\HttpFoundation\Response;

class GithubWebhookTest extends WebTestCase
{
	private KernelBrowser $kernelBrowser;

	private function initServices(): void
	{
		$this->kernelBrowser = self::createClient();
	}

	public function testWebhook(): void
	{
		$this->initServices();

		$i = 0;
		while (true) {
			$payload = match (++$i) {
				1 => $this->getPingPayload(),
				2 => $this->getIssueAssignedPayload(),
				3 => $this->getIssueOpenGitlabPayloadString(),
				4 => $this->getIssueOpenGiteaPayloadString(),
				5 => $this->getIssueOpenPayloadString(),
				6 => $this->getIssueOpenPayloadRepo(),
				7 => $this->getIssueClosedPayload(),
				default => null,
			};
			if (null === $payload) {
				break;
			}
			$uri = 3 === $i ? '/webhook/gitlab' : '/webhook/github';
			$this->assertPayload($payload, $uri);
		}
	}

	private function assertPayload(array $payload, string $uri): void
	{
		$this->kernelBrowser->request('POST', $uri, [], [], [], json_encode($payload));

		$statusCode = $this->kernelBrowser->getResponse()->getStatusCode();
		$this->assertEquals(Response::HTTP_ACCEPTED, $statusCode);
	}

	private function getIssueAssignedPayload(): array
	{
		return [
			'action' => 'assigned',
			'issue' => [
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5',
				'repository_url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/labels{/name}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/comments',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/events',
				'html_url' => 'https://github.com/marsender/symfony-webhook/issues/5',
				'id' => 2206273214,
				'node_id' => 'I_kwDOLk3wls6DgQ6-',
				'number' => 5,
				'title' => 'Add code coverage and badge',
				'user' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'labels' => [],
				'state' => 'open',
				'locked' => false,
				'assignee' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'assignees' => [
					[
						'login' => 'marsender',
						'id' => 279979,
						'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
						'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
						'gravatar_id' => '',
						'url' => 'https://api.github.com/users/marsender',
						'html_url' => 'https://github.com/marsender',
						'followers_url' => 'https://api.github.com/users/marsender/followers',
						'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
						'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
						'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
						'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
						'organizations_url' => 'https://api.github.com/users/marsender/orgs',
						'repos_url' => 'https://api.github.com/users/marsender/repos',
						'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
						'received_events_url' => 'https://api.github.com/users/marsender/received_events',
						'type' => 'User',
						'site_admin' => false,
					],
				],
				'milestone' => null,
				'comments' => 0,
				'created_at' => '2024-03-25T17:11:54Z',
				'updated_at' => '2024-03-25T17:11:54Z',
				'closed_at' => null,
				'author_association' => 'OWNER',
				'active_lock_reason' => null,
				'body' => null,
				'reactions' => [
					'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/reactions',
					'total_count' => 0,
					'+1' => 0,
					0,
					'laugh' => 0,
					'hooray' => 0,
					'confused' => 0,
					'heart' => 0,
					'rocket' => 0,
					'eyes' => 0,
				],
				'timeline_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/timeline',
				'performed_via_github_app' => null,
				'state_reason' => null,
			],
			'assignee' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
			'repository' => [
				'id' => 776859798,
				'node_id' => 'R_kgDOLk3wlg',
				'name' => 'symfony-webhook',
				'full_name' => 'marsender/symfony-webhook',
				'private' => true,
				'owner' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'html_url' => 'https://github.com/marsender/symfony-webhook',
				'description' => null,
				'fork' => false,
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'forks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/forks',
				'keys_url' => 'https://api.github.com/repos/marsender/symfony-webhook/keys{/key_id}',
				'collaborators_url' => 'https://api.github.com/repos/marsender/symfony-webhook/collaborators{/collaborator}',
				'teams_url' => 'https://api.github.com/repos/marsender/symfony-webhook/teams',
				'hooks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/hooks',
				'issue_events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/events{/number}',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/events',
				'assignees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/assignees{/user}',
				'branches_url' => 'https://api.github.com/repos/marsender/symfony-webhook/branches{/branch}',
				'tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/tags',
				'blobs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/blobs{/sha}',
				'git_tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/tags{/sha}',
				'git_refs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/refs{/sha}',
				'trees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/trees{/sha}',
				'statuses_url' => 'https://api.github.com/repos/marsender/symfony-webhook/statuses/{sha}',
				'languages_url' => 'https://api.github.com/repos/marsender/symfony-webhook/languages',
				'stargazers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/stargazers',
				'contributors_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contributors',
				'subscribers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscribers',
				'subscription_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscription',
				'commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/commits{/sha}',
				'git_commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/commits{/sha}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/comments{/number}',
				'issue_comment_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/comments{/number}',
				'contents_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contents/{+path}',
				'compare_url' => 'https://api.github.com/repos/marsender/symfony-webhook/compare/{base}...{head}',
				'merges_url' => 'https://api.github.com/repos/marsender/symfony-webhook/merges',
				'archive_url' => 'https://api.github.com/repos/marsender/symfony-webhook/{archive_format}{/ref}',
				'downloads_url' => 'https://api.github.com/repos/marsender/symfony-webhook/downloads',
				'issues_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues{/number}',
				'pulls_url' => 'https://api.github.com/repos/marsender/symfony-webhook/pulls{/number}',
				'milestones_url' => 'https://api.github.com/repos/marsender/symfony-webhook/milestones{/number}',
				'notifications_url' => 'https://api.github.com/repos/marsender/symfony-webhook/notifications{?since,all,participating}',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/labels{/name}',
				'releases_url' => 'https://api.github.com/repos/marsender/symfony-webhook/releases{/id}',
				'deployments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/deployments',
				'created_at' => '2024-03-24T16:40:06Z',
				'updated_at' => '2024-03-24T16:59:34Z',
				'pushed_at' => '2024-03-25T17:12:30Z',
				'git_url' => 'git://github.com/marsender/symfony-webhook.git',
				'ssh_url' => 'git@github.com:marsender/symfony-webhook.git',
				'clone_url' => 'https://github.com/marsender/symfony-webhook.git',
				'svn_url' => 'https://github.com/marsender/symfony-webhook',
				'homepage' => null,
				'size' => 220,
				'stargazers_count' => 0,
				'watchers_count' => 0,
				'language' => 'PHP',
				'has_issues' => true,
				'has_projects' => true,
				'has_downloads' => true,
				'has_wiki' => false,
				'has_pages' => false,
				'has_discussions' => false,
				'forks_count' => 0,
				'mirror_url' => null,
				'archived' => false,
				'disabled' => false,
				'open_issues_count' => 2,
				'license' => null,
				'allow_forking' => true,
				'is_template' => false,
				'web_commit_signoff_required' => false,
				'topics' => [],
				'visibility' => 'private',
				'forks' => 0,
				'open_issues' => 2,
				'watchers' => 0,
				'default_branch' => 'main',
			],
			'sender' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
		];
	}

	private function getIssueOpenGitlabPayloadString(): array
	{
		return json_decode('
		{
			"object_kind": "issue",
			"event_type": "issue",
			"user": {
				"id": 15684224,
				"name": "Didier Corbière",
				"username": "marsender",
				"avatar_url": "https://secure.gravatar.com/avatar/18a0752f34d746dd378e23fad0f37af51a354e0d42d577f575ba59e72a872b62?s=80&d=identicon",
				"email": "[REDACTED]"
			},
			"project": {
				"id": 57869270,
				"name": "ws-website",
				"description": null,
				"web_url": "https://gitlab.com/workingshare/ws-website",
				"avatar_url": null,
				"git_ssh_url": "git@gitlab.com:workingshare/ws-website.git",
				"git_http_url": "https://gitlab.com/workingshare/ws-website.git",
				"namespace": "WorkingShare",
				"visibility_level": 0,
				"path_with_namespace": "workingshare/ws-website",
				"default_branch": "main",
				"ci_config_path": "",
				"homepage": "https://gitlab.com/workingshare/ws-website",
				"url": "git@gitlab.com:workingshare/ws-website.git",
				"ssh_url": "git@gitlab.com:workingshare/ws-website.git",
				"http_url": "https://gitlab.com/workingshare/ws-website.git"
			},
			"object_attributes": {
				"author_id": 15684224,
				"closed_at": null,
				"confidential": false,
				"created_at": "2024-05-23 09:46:27 UTC",
				"description": "",
				"discussion_locked": null,
				"due_date": null,
				"id": 146940757,
				"iid": 1,
				"last_edited_at": null,
				"last_edited_by_id": null,
				"milestone_id": null,
				"moved_to_id": null,
				"duplicated_to_id": null,
				"project_id": 57869270,
				"relative_position": null,
				"state_id": 1,
				"time_estimate": 0,
				"title": "Webhook test for WorkingShare GitLab projects",
				"updated_at": "2024-05-23 09:46:27 UTC",
				"updated_by_id": null,
				"weight": null,
				"health_status": null,
				"url": "https://gitlab.com/workingshare/ws-website/-/issues/1",
				"total_time_spent": 0,
				"time_change": 0,
				"human_total_time_spent": null,
				"human_time_change": null,
				"human_time_estimate": null,
				"assignee_ids": [
					15684224
				],
				"assignee_id": 15684224,
				"labels": [
		
				],
				"state": "opened",
				"severity": "unknown",
				"customer_relations_contacts": [
		
				],
				"action": "open"
			},
			"labels": [
		
			],
			"changes": {
				"author_id": {
					"previous": null,
					"current": 15684224
				},
				"created_at": {
					"previous": null,
					"current": "2024-05-23 09:46:27 UTC"
				},
				"description": {
					"previous": null,
					"current": ""
				},
				"id": {
					"previous": null,
					"current": 146940757
				},
				"iid": {
					"previous": null,
					"current": 1
				},
				"project_id": {
					"previous": null,
					"current": 57869270
				},
				"time_estimate": {
					"previous": null,
					"current": 0
				},
				"title": {
					"previous": null,
					"current": "Test GitLab webhook for issues"
				},
				"updated_at": {
					"previous": null,
					"current": "2024-05-23 09:46:27 UTC"
				}
			},
			"repository": {
				"name": "ws-website",
				"url": "git@gitlab.com:workingshare/ws-website.git",
				"description": null,
				"homepage": "https://gitlab.com/workingshare/ws-website"
			},
			"assignees": [
				{
					"id": 15684224,
					"name": "Didier Corbière",
					"username": "marsender",
					"avatar_url": "https://secure.gravatar.com/avatar/18a0752f34d746dd378e23fad0f37af51a354e0d42d577f575ba59e72a872b62?s=80&d=identicon",
					"email": "[REDACTED]"
				}
			]
		}
		', true);
	}

	private function getIssueOpenGiteaPayloadString(): array
	{
		return json_decode('
		{
			"action": "opened",
			"number": 60,
			"issue": {
				"id": 425,
				"url": "https://git.classiques-garnier.net/api/v1/repos/classiques-garnier/garnier_prod/issues/60",
				"html_url": "https://git.classiques-garnier.net/classiques-garnier/garnier_prod/issues/60",
				"number": 60,
				"user": {
					"id": 3,
					"login": "marsender",
					"login_name": "",
					"full_name": "Didier Corbière",
					"email": "marsender@noreply.localhost",
					"avatar_url": "https://git.classiques-garnier.net/avatars/c1ebeea953286a0838af1c2e10fa1eb8",
					"language": "",
					"is_admin": false,
					"last_login": "0001-01-01T00:00:00Z",
					"created": "2022-08-01T14:31:24Z",
					"restricted": false,
					"active": false,
					"prohibit_login": false,
					"location": "",
					"website": "",
					"description": "",
					"visibility": "public",
					"followers_count": 0,
					"following_count": 0,
					"starred_repos_count": 4,
					"username": "marsender"
				},
				"original_author": "",
				"original_author_id": 0,
				"title": "Webhook test for Garnier gitea projects",
				"body": "This is the issue comment.",
				"ref": "",
				"assets": [],
				"labels": [],
				"milestone": null,
				"assignee": {
					"id": 3,
					"login": "marsender",
					"login_name": "",
					"full_name": "Didier Corbière",
					"email": "marsender@noreply.localhost",
					"avatar_url": "https://git.classiques-garnier.net/avatars/c1ebeea953286a0838af1c2e10fa1eb8",
					"language": "",
					"is_admin": false,
					"last_login": "0001-01-01T00:00:00Z",
					"created": "2022-08-01T14:31:24Z",
					"restricted": false,
					"active": false,
					"prohibit_login": false,
					"location": "",
					"website": "",
					"description": "",
					"visibility": "public",
					"followers_count": 0,
					"following_count": 0,
					"starred_repos_count": 4,
					"username": "marsender"
				},
				"assignees": [
					{
						"id": 3,
						"login": "marsender",
						"login_name": "",
						"full_name": "Didier Corbière",
						"email": "marsender@noreply.localhost",
						"avatar_url": "https://git.classiques-garnier.net/avatars/c1ebeea953286a0838af1c2e10fa1eb8",
						"language": "",
						"is_admin": false,
						"last_login": "0001-01-01T00:00:00Z",
						"created": "2022-08-01T14:31:24Z",
						"restricted": false,
						"active": false,
						"prohibit_login": false,
						"location": "",
						"website": "",
						"description": "",
						"visibility": "public",
						"followers_count": 0,
						"following_count": 0,
						"starred_repos_count": 4,
						"username": "marsender"
					}
				],
				"state": "open",
				"is_locked": false,
				"comments": 0,
				"created_at": "2024-05-22T06:20:28Z",
				"updated_at": "2024-05-22T06:20:28Z",
				"closed_at": null,
				"due_date": null,
				"pull_request": null,
				"repository": {
					"id": 4,
					"name": "garnier_prod",
					"owner": "classiques-garnier",
					"full_name": "classiques-garnier/garnier_prod"
				},
				"pin_order": 0
			},
			"repository": {
				"id": 4,
				"owner": {
					"id": 2,
					"login": "classiques-garnier",
					"login_name": "",
					"full_name": "Classiques Garnier",
					"email": "",
					"avatar_url": "https://git.classiques-garnier.net/avatars/65fffc9b68e33495f4d2308c43c2ee15",
					"language": "",
					"is_admin": false,
					"last_login": "0001-01-01T00:00:00Z",
					"created": "2022-08-01T14:07:17Z",
					"restricted": false,
					"active": false,
					"prohibit_login": false,
					"location": "Paris, France",
					"website": "https://classiques-garnier.com",
					"description": "",
					"visibility": "limited",
					"followers_count": 0,
					"following_count": 0,
					"starred_repos_count": 0,
					"username": "classiques-garnier"
				},
				"name": "garnier_prod",
				"full_name": "classiques-garnier/garnier_prod",
				"description": "",
				"empty": false,
				"private": false,
				"fork": false,
				"template": false,
				"parent": null,
				"mirror": false,
				"size": 12110,
				"language": "",
				"languages_url": "https://git.classiques-garnier.net/api/v1/repos/classiques-garnier/garnier_prod/languages",
				"html_url": "https://git.classiques-garnier.net/classiques-garnier/garnier_prod",
				"url": "https://git.classiques-garnier.net/api/v1/repos/classiques-garnier/garnier_prod",
				"link": "",
				"ssh_url": "git@git.classiques-garnier.net:classiques-garnier/garnier_prod.git",
				"clone_url": "https://git.classiques-garnier.net/classiques-garnier/garnier_prod.git",
				"original_url": "",
				"website": "",
				"stars_count": 1,
				"forks_count": 0,
				"watchers_count": 2,
				"open_issues_count": 3,
				"open_pr_counter": 1,
				"release_counter": 0,
				"default_branch": "master",
				"archived": false,
				"created_at": "2022-08-11T14:10:32Z",
				"updated_at": "2024-05-17T17:49:15Z",
				"archived_at": "1970-01-01T00:00:00Z",
				"permissions": {
					"admin": true,
					"push": true,
					"pull": true
				},
				"has_issues": true,
				"internal_tracker": {
					"enable_time_tracker": true,
					"allow_only_contributors_to_track_time": true,
					"enable_issue_dependencies": true
				},
				"has_wiki": true,
				"has_pull_requests": true,
				"has_projects": true,
				"has_releases": true,
				"has_packages": false,
				"has_actions": false,
				"ignore_whitespace_conflicts": false,
				"allow_merge_commits": true,
				"allow_rebase": true,
				"allow_rebase_explicit": true,
				"allow_squash_merge": true,
				"allow_rebase_update": true,
				"default_delete_branch_after_merge": false,
				"default_merge_style": "merge",
				"default_allow_maintainer_edit": false,
				"avatar_url": "",
				"internal": false,
				"mirror_interval": "",
				"mirror_updated": "0001-01-01T00:00:00Z",
				"repo_transfer": null
			},
			"sender": {
				"id": 3,
				"login": "marsender",
				"login_name": "",
				"full_name": "Didier Corbière",
				"email": "marsender@noreply.localhost",
				"avatar_url": "https://git.classiques-garnier.net/avatars/c1ebeea953286a0838af1c2e10fa1eb8",
				"language": "",
				"is_admin": false,
				"last_login": "0001-01-01T00:00:00Z",
				"created": "2022-08-01T14:31:24Z",
				"restricted": false,
				"active": false,
				"prohibit_login": false,
				"location": "",
				"website": "",
				"description": "",
				"visibility": "public",
				"followers_count": 0,
				"following_count": 0,
				"starred_repos_count": 4,
				"username": "marsender"
			},
			"commit_id": ""
		}
		', true);
	}

	private function getIssueOpenPayloadString(): array
	{
		return json_decode('
		{
			"action": "opened",
			"issue": {
				"url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15",
				"repository_url": "https://api.github.com/repos/marsender/symfony-webhook",
				"labels_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15/labels{/name}",
				"comments_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15/comments",
				"events_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15/events",
				"html_url": "https://github.com/marsender/symfony-webhook/issues/15",
				"id": 2274590737,
				"node_id": "I_kwDOLk3wls6Hk4AR",
				"number": 15,
				"title": "Webhook test for Opale projects",
				"user": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"labels": [
		
				],
				"state": "open",
				"locked": false,
				"assignee": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"assignees": [
					{
						"login": "marsender",
						"id": 279979,
						"node_id": "MDQ6VXNlcjI3OTk3OQ==",
						"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/marsender",
						"html_url": "https://github.com/marsender",
						"followers_url": "https://api.github.com/users/marsender/followers",
						"following_url": "https://api.github.com/users/marsender/following{/other_user}",
						"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
						"organizations_url": "https://api.github.com/users/marsender/orgs",
						"repos_url": "https://api.github.com/users/marsender/repos",
						"events_url": "https://api.github.com/users/marsender/events{/privacy}",
						"received_events_url": "https://api.github.com/users/marsender/received_events",
						"type": "User",
						"site_admin": false
					}
				],
				"milestone": null,
				"comments": 0,
				"created_at": "2024-05-02T04:43:53Z",
				"updated_at": "2024-05-02T04:43:54Z",
				"closed_at": null,
				"author_association": "OWNER",
				"active_lock_reason": null,
				"body": null,
				"reactions": {
					"url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15/reactions",
					"total_count": 0,
					"+1": 0,
					"-1": 0,
					"laugh": 0,
					"hooray": 0,
					"confused": 0,
					"heart": 0,
					"rocket": 0,
					"eyes": 0
				},
				"timeline_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/15/timeline",
				"performed_via_github_app": null,
				"state_reason": null
			},
			"repository": {
				"id": 776859798,
				"node_id": "R_kgDOLk3wlg",
				"name": "symfony-webhook",
				"full_name": "marsender/symfony-webhook",
				"private": false,
				"owner": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"html_url": "https://github.com/marsender/symfony-webhook",
				"description": null,
				"fork": false,
				"url": "https://api.github.com/repos/marsender/symfony-webhook",
				"forks_url": "https://api.github.com/repos/marsender/symfony-webhook/forks",
				"keys_url": "https://api.github.com/repos/marsender/symfony-webhook/keys{/key_id}",
				"collaborators_url": "https://api.github.com/repos/marsender/symfony-webhook/collaborators{/collaborator}",
				"teams_url": "https://api.github.com/repos/marsender/symfony-webhook/teams",
				"hooks_url": "https://api.github.com/repos/marsender/symfony-webhook/hooks",
				"issue_events_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/events{/number}",
				"events_url": "https://api.github.com/repos/marsender/symfony-webhook/events",
				"assignees_url": "https://api.github.com/repos/marsender/symfony-webhook/assignees{/user}",
				"branches_url": "https://api.github.com/repos/marsender/symfony-webhook/branches{/branch}",
				"tags_url": "https://api.github.com/repos/marsender/symfony-webhook/tags",
				"blobs_url": "https://api.github.com/repos/marsender/symfony-webhook/git/blobs{/sha}",
				"git_tags_url": "https://api.github.com/repos/marsender/symfony-webhook/git/tags{/sha}",
				"git_refs_url": "https://api.github.com/repos/marsender/symfony-webhook/git/refs{/sha}",
				"trees_url": "https://api.github.com/repos/marsender/symfony-webhook/git/trees{/sha}",
				"statuses_url": "https://api.github.com/repos/marsender/symfony-webhook/statuses/{sha}",
				"languages_url": "https://api.github.com/repos/marsender/symfony-webhook/languages",
				"stargazers_url": "https://api.github.com/repos/marsender/symfony-webhook/stargazers",
				"contributors_url": "https://api.github.com/repos/marsender/symfony-webhook/contributors",
				"subscribers_url": "https://api.github.com/repos/marsender/symfony-webhook/subscribers",
				"subscription_url": "https://api.github.com/repos/marsender/symfony-webhook/subscription",
				"commits_url": "https://api.github.com/repos/marsender/symfony-webhook/commits{/sha}",
				"git_commits_url": "https://api.github.com/repos/marsender/symfony-webhook/git/commits{/sha}",
				"comments_url": "https://api.github.com/repos/marsender/symfony-webhook/comments{/number}",
				"issue_comment_url": "https://api.github.com/repos/marsender/symfony-webhook/issues/comments{/number}",
				"contents_url": "https://api.github.com/repos/marsender/symfony-webhook/contents/{+path}",
				"compare_url": "https://api.github.com/repos/marsender/symfony-webhook/compare/{base}...{head}",
				"merges_url": "https://api.github.com/repos/marsender/symfony-webhook/merges",
				"archive_url": "https://api.github.com/repos/marsender/symfony-webhook/{archive_format}{/ref}",
				"downloads_url": "https://api.github.com/repos/marsender/symfony-webhook/downloads",
				"issues_url": "https://api.github.com/repos/marsender/symfony-webhook/issues{/number}",
				"pulls_url": "https://api.github.com/repos/marsender/symfony-webhook/pulls{/number}",
				"milestones_url": "https://api.github.com/repos/marsender/symfony-webhook/milestones{/number}",
				"notifications_url": "https://api.github.com/repos/marsender/symfony-webhook/notifications{?since,all,participating}",
				"labels_url": "https://api.github.com/repos/marsender/symfony-webhook/labels{/name}",
				"releases_url": "https://api.github.com/repos/marsender/symfony-webhook/releases{/id}",
				"deployments_url": "https://api.github.com/repos/marsender/symfony-webhook/deployments",
				"created_at": "2024-03-24T16:40:06Z",
				"updated_at": "2024-05-02T04:31:51Z",
				"pushed_at": "2024-05-02T04:31:48Z",
				"git_url": "git://github.com/marsender/symfony-webhook.git",
				"ssh_url": "git@github.com:marsender/symfony-webhook.git",
				"clone_url": "https://github.com/marsender/symfony-webhook.git",
				"svn_url": "https://github.com/marsender/symfony-webhook",
				"homepage": null,
				"size": 431,
				"stargazers_count": 0,
				"watchers_count": 0,
				"language": "PHP",
				"has_issues": true,
				"has_projects": true,
				"has_downloads": true,
				"has_wiki": false,
				"has_pages": false,
				"has_discussions": false,
				"forks_count": 0,
				"mirror_url": null,
				"archived": false,
				"disabled": false,
				"open_issues_count": 1,
				"license": {
					"key": "agpl-3.0",
					"name": "GNU Affero General Public License v3.0",
					"spdx_id": "AGPL-3.0",
					"url": "https://api.github.com/licenses/agpl-3.0",
					"node_id": "MDc6TGljZW5zZTE="
				},
				"allow_forking": true,
				"is_template": false,
				"web_commit_signoff_required": false,
				"topics": [
		
				],
				"visibility": "public",
				"forks": 0,
				"open_issues": 1,
				"watchers": 0,
				"default_branch": "main"
			},
			"sender": {
				"login": "marsender",
				"id": 279979,
				"node_id": "MDQ6VXNlcjI3OTk3OQ==",
				"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/marsender",
				"html_url": "https://github.com/marsender",
				"followers_url": "https://api.github.com/users/marsender/followers",
				"following_url": "https://api.github.com/users/marsender/following{/other_user}",
				"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
				"organizations_url": "https://api.github.com/users/marsender/orgs",
				"repos_url": "https://api.github.com/users/marsender/repos",
				"events_url": "https://api.github.com/users/marsender/events{/privacy}",
				"received_events_url": "https://api.github.com/users/marsender/received_events",
				"type": "User",
				"site_admin": false
			}
		}
		', true);
	}

	private function getIssueOpenPayloadRepo(): array
	{
		return json_decode('
		{
			"action": "opened",
			"issue": {
				"url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71",
				"repository_url": "https://api.github.com/repos/QDZantoine/spot-to-work",
				"labels_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71/labels{/name}",
				"comments_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71/comments",
				"events_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71/events",
				"html_url": "https://github.com/QDZantoine/spot-to-work/issues/71",
				"id": 2234971438,
				"node_id": "I_kwDOLfwTAM6FNvUu",
				"number": 71,
				"title": "Webhook test for Antoine projects",
				"user": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"labels": [
		
				],
				"state": "open",
				"locked": false,
				"assignee": {
					"login": "marsender",
					"id": 279979,
					"node_id": "MDQ6VXNlcjI3OTk3OQ==",
					"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/marsender",
					"html_url": "https://github.com/marsender",
					"followers_url": "https://api.github.com/users/marsender/followers",
					"following_url": "https://api.github.com/users/marsender/following{/other_user}",
					"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
					"organizations_url": "https://api.github.com/users/marsender/orgs",
					"repos_url": "https://api.github.com/users/marsender/repos",
					"events_url": "https://api.github.com/users/marsender/events{/privacy}",
					"received_events_url": "https://api.github.com/users/marsender/received_events",
					"type": "User",
					"site_admin": false
				},
				"assignees": [
					{
						"login": "marsender",
						"id": 279979,
						"node_id": "MDQ6VXNlcjI3OTk3OQ==",
						"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/marsender",
						"html_url": "https://github.com/marsender",
						"followers_url": "https://api.github.com/users/marsender/followers",
						"following_url": "https://api.github.com/users/marsender/following{/other_user}",
						"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
						"organizations_url": "https://api.github.com/users/marsender/orgs",
						"repos_url": "https://api.github.com/users/marsender/repos",
						"events_url": "https://api.github.com/users/marsender/events{/privacy}",
						"received_events_url": "https://api.github.com/users/marsender/received_events",
						"type": "User",
						"site_admin": false
					},
					{
						"login": "QDZantoine",
						"id": 146669492,
						"node_id": "U_kgDOCL3_tA",
						"avatar_url": "https://avatars.githubusercontent.com/u/146669492?v=4",
						"gravatar_id": "",
						"url": "https://api.github.com/users/QDZantoine",
						"html_url": "https://github.com/QDZantoine",
						"followers_url": "https://api.github.com/users/QDZantoine/followers",
						"following_url": "https://api.github.com/users/QDZantoine/following{/other_user}",
						"gists_url": "https://api.github.com/users/QDZantoine/gists{/gist_id}",
						"starred_url": "https://api.github.com/users/QDZantoine/starred{/owner}{/repo}",
						"subscriptions_url": "https://api.github.com/users/QDZantoine/subscriptions",
						"organizations_url": "https://api.github.com/users/QDZantoine/orgs",
						"repos_url": "https://api.github.com/users/QDZantoine/repos",
						"events_url": "https://api.github.com/users/QDZantoine/events{/privacy}",
						"received_events_url": "https://api.github.com/users/QDZantoine/received_events",
						"type": "User",
						"site_admin": false
					}
				],
				"milestone": null,
				"comments": 0,
				"created_at": "2024-04-10T07:49:23Z",
				"updated_at": "2024-04-10T07:49:23Z",
				"closed_at": null,
				"author_association": "COLLABORATOR",
				"active_lock_reason": null,
				"body": null,
				"reactions": {
					"url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71/reactions",
					"total_count": 0,
					"+1": 0,
					"-1": 0,
					"laugh": 0,
					"hooray": 0,
					"confused": 0,
					"heart": 0,
					"rocket": 0,
					"eyes": 0
				},
				"timeline_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/71/timeline",
				"performed_via_github_app": null,
				"state_reason": null
			},
			"repository": {
				"id": 771494656,
				"node_id": "R_kgDOLfwTAA",
				"name": "spot-to-work",
				"full_name": "QDZantoine/spot-to-work",
				"private": true,
				"owner": {
					"login": "QDZantoine",
					"id": 146669492,
					"node_id": "U_kgDOCL3_tA",
					"avatar_url": "https://avatars.githubusercontent.com/u/146669492?v=4",
					"gravatar_id": "",
					"url": "https://api.github.com/users/QDZantoine",
					"html_url": "https://github.com/QDZantoine",
					"followers_url": "https://api.github.com/users/QDZantoine/followers",
					"following_url": "https://api.github.com/users/QDZantoine/following{/other_user}",
					"gists_url": "https://api.github.com/users/QDZantoine/gists{/gist_id}",
					"starred_url": "https://api.github.com/users/QDZantoine/starred{/owner}{/repo}",
					"subscriptions_url": "https://api.github.com/users/QDZantoine/subscriptions",
					"organizations_url": "https://api.github.com/users/QDZantoine/orgs",
					"repos_url": "https://api.github.com/users/QDZantoine/repos",
					"events_url": "https://api.github.com/users/QDZantoine/events{/privacy}",
					"received_events_url": "https://api.github.com/users/QDZantoine/received_events",
					"type": "User",
					"site_admin": false
				},
				"html_url": "https://github.com/QDZantoine/spot-to-work",
				"description": null,
				"fork": false,
				"url": "https://api.github.com/repos/QDZantoine/spot-to-work",
				"forks_url": "https://api.github.com/repos/QDZantoine/spot-to-work/forks",
				"keys_url": "https://api.github.com/repos/QDZantoine/spot-to-work/keys{/key_id}",
				"collaborators_url": "https://api.github.com/repos/QDZantoine/spot-to-work/collaborators{/collaborator}",
				"teams_url": "https://api.github.com/repos/QDZantoine/spot-to-work/teams",
				"hooks_url": "https://api.github.com/repos/QDZantoine/spot-to-work/hooks",
				"issue_events_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/events{/number}",
				"events_url": "https://api.github.com/repos/QDZantoine/spot-to-work/events",
				"assignees_url": "https://api.github.com/repos/QDZantoine/spot-to-work/assignees{/user}",
				"branches_url": "https://api.github.com/repos/QDZantoine/spot-to-work/branches{/branch}",
				"tags_url": "https://api.github.com/repos/QDZantoine/spot-to-work/tags",
				"blobs_url": "https://api.github.com/repos/QDZantoine/spot-to-work/git/blobs{/sha}",
				"git_tags_url": "https://api.github.com/repos/QDZantoine/spot-to-work/git/tags{/sha}",
				"git_refs_url": "https://api.github.com/repos/QDZantoine/spot-to-work/git/refs{/sha}",
				"trees_url": "https://api.github.com/repos/QDZantoine/spot-to-work/git/trees{/sha}",
				"statuses_url": "https://api.github.com/repos/QDZantoine/spot-to-work/statuses/{sha}",
				"languages_url": "https://api.github.com/repos/QDZantoine/spot-to-work/languages",
				"stargazers_url": "https://api.github.com/repos/QDZantoine/spot-to-work/stargazers",
				"contributors_url": "https://api.github.com/repos/QDZantoine/spot-to-work/contributors",
				"subscribers_url": "https://api.github.com/repos/QDZantoine/spot-to-work/subscribers",
				"subscription_url": "https://api.github.com/repos/QDZantoine/spot-to-work/subscription",
				"commits_url": "https://api.github.com/repos/QDZantoine/spot-to-work/commits{/sha}",
				"git_commits_url": "https://api.github.com/repos/QDZantoine/spot-to-work/git/commits{/sha}",
				"comments_url": "https://api.github.com/repos/QDZantoine/spot-to-work/comments{/number}",
				"issue_comment_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues/comments{/number}",
				"contents_url": "https://api.github.com/repos/QDZantoine/spot-to-work/contents/{+path}",
				"compare_url": "https://api.github.com/repos/QDZantoine/spot-to-work/compare/{base}...{head}",
				"merges_url": "https://api.github.com/repos/QDZantoine/spot-to-work/merges",
				"archive_url": "https://api.github.com/repos/QDZantoine/spot-to-work/{archive_format}{/ref}",
				"downloads_url": "https://api.github.com/repos/QDZantoine/spot-to-work/downloads",
				"issues_url": "https://api.github.com/repos/QDZantoine/spot-to-work/issues{/number}",
				"pulls_url": "https://api.github.com/repos/QDZantoine/spot-to-work/pulls{/number}",
				"milestones_url": "https://api.github.com/repos/QDZantoine/spot-to-work/milestones{/number}",
				"notifications_url": "https://api.github.com/repos/QDZantoine/spot-to-work/notifications{?since,all,participating}",
				"labels_url": "https://api.github.com/repos/QDZantoine/spot-to-work/labels{/name}",
				"releases_url": "https://api.github.com/repos/QDZantoine/spot-to-work/releases{/id}",
				"deployments_url": "https://api.github.com/repos/QDZantoine/spot-to-work/deployments",
				"created_at": "2024-03-13T12:01:54Z",
				"updated_at": "2024-03-15T10:26:58Z",
				"pushed_at": "2024-04-09T15:38:27Z",
				"git_url": "git://github.com/QDZantoine/spot-to-work.git",
				"ssh_url": "git@github.com:QDZantoine/spot-to-work.git",
				"clone_url": "https://github.com/QDZantoine/spot-to-work.git",
				"svn_url": "https://github.com/QDZantoine/spot-to-work",
				"homepage": null,
				"size": 4497,
				"stargazers_count": 1,
				"watchers_count": 1,
				"language": "PHP",
				"has_issues": true,
				"has_projects": true,
				"has_downloads": true,
				"has_wiki": false,
				"has_pages": false,
				"has_discussions": false,
				"forks_count": 0,
				"mirror_url": null,
				"archived": false,
				"disabled": false,
				"open_issues_count": 2,
				"license": null,
				"allow_forking": true,
				"is_template": false,
				"web_commit_signoff_required": false,
				"topics": [
		
				],
				"visibility": "private",
				"forks": 0,
				"open_issues": 2,
				"watchers": 1,
				"default_branch": "master"
			},
			"sender": {
				"login": "marsender",
				"id": 279979,
				"node_id": "MDQ6VXNlcjI3OTk3OQ==",
				"avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
				"gravatar_id": "",
				"url": "https://api.github.com/users/marsender",
				"html_url": "https://github.com/marsender",
				"followers_url": "https://api.github.com/users/marsender/followers",
				"following_url": "https://api.github.com/users/marsender/following{/other_user}",
				"gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
				"starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
				"subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
				"organizations_url": "https://api.github.com/users/marsender/orgs",
				"repos_url": "https://api.github.com/users/marsender/repos",
				"events_url": "https://api.github.com/users/marsender/events{/privacy}",
				"received_events_url": "https://api.github.com/users/marsender/received_events",
				"type": "User",
				"site_admin": false
			}
		}
		', true);
	}

	private function getIssueClosedPayload(): array
	{
		return [
			'action' => 'closed',
			'issue' => [
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5',
				'repository_url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/labels{/name}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/comments',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/events',
				'html_url' => 'https://github.com/marsender/symfony-webhook/issues/5',
				'id' => 2206273214,
				'node_id' => 'I_kwDOLk3wls6DgQ6-',
				'number' => 5,
				'title' => 'Add code coverage and badge',
				'user' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'labels' => [],
				'state' => 'closed',
				'locked' => false,
				'assignee' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'assignees' => [
					[
						'login' => 'marsender',
						'id' => 279979,
						'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
						'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
						'gravatar_id' => '',
						'url' => 'https://api.github.com/users/marsender',
						'html_url' => 'https://github.com/marsender',
						'followers_url' => 'https://api.github.com/users/marsender/followers',
						'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
						'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
						'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
						'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
						'organizations_url' => 'https://api.github.com/users/marsender/orgs',
						'repos_url' => 'https://api.github.com/users/marsender/repos',
						'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
						'received_events_url' => 'https://api.github.com/users/marsender/received_events',
						'type' => 'User',
						'site_admin' => false,
					],
				],
				'milestone' => null,
				'comments' => 0,
				'created_at' => '2024-03-25T17:11:54Z',
				'updated_at' => '2024-03-26T06:55:18Z',
				'closed_at' => '2024-03-26T06:55:18Z',
				'author_association' => 'OWNER',
				'active_lock_reason' => null,
				'body' => null,
				'reactions' => [
					'url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/reactions',
					'total_count' => 0,
					'+1' => 0,
					0,
					'laugh' => 0,
					'hooray' => 0,
					'confused' => 0,
					'heart' => 0,
					'rocket' => 0,
					'eyes' => 0,
				],
				'timeline_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/5/timeline',
				'performed_via_github_app' => null,
				'state_reason' => 'completed',
			],
			'repository' => [
				'id' => 776859798,
				'node_id' => 'R_kgDOLk3wlg',
				'name' => 'symfony-webhook',
				'full_name' => 'marsender/symfony-webhook',
				'private' => true,
				'owner' => [
					'login' => 'marsender',
					'id' => 279979,
					'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
					'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
					'gravatar_id' => '',
					'url' => 'https://api.github.com/users/marsender',
					'html_url' => 'https://github.com/marsender',
					'followers_url' => 'https://api.github.com/users/marsender/followers',
					'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
					'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
					'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
					'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
					'organizations_url' => 'https://api.github.com/users/marsender/orgs',
					'repos_url' => 'https://api.github.com/users/marsender/repos',
					'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
					'received_events_url' => 'https://api.github.com/users/marsender/received_events',
					'type' => 'User',
					'site_admin' => false,
				],
				'html_url' => 'https://github.com/marsender/symfony-webhook',
				'description' => null,
				'fork' => false,
				'url' => 'https://api.github.com/repos/marsender/symfony-webhook',
				'forks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/forks',
				'keys_url' => 'https://api.github.com/repos/marsender/symfony-webhook/keys{/key_id}',
				'collaborators_url' => 'https://api.github.com/repos/marsender/symfony-webhook/collaborators{/collaborator}',
				'teams_url' => 'https://api.github.com/repos/marsender/symfony-webhook/teams',
				'hooks_url' => 'https://api.github.com/repos/marsender/symfony-webhook/hooks',
				'issue_events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/events{/number}',
				'events_url' => 'https://api.github.com/repos/marsender/symfony-webhook/events',
				'assignees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/assignees{/user}',
				'branches_url' => 'https://api.github.com/repos/marsender/symfony-webhook/branches{/branch}',
				'tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/tags',
				'blobs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/blobs{/sha}',
				'git_tags_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/tags{/sha}',
				'git_refs_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/refs{/sha}',
				'trees_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/trees{/sha}',
				'statuses_url' => 'https://api.github.com/repos/marsender/symfony-webhook/statuses/{sha}',
				'languages_url' => 'https://api.github.com/repos/marsender/symfony-webhook/languages',
				'stargazers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/stargazers',
				'contributors_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contributors',
				'subscribers_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscribers',
				'subscription_url' => 'https://api.github.com/repos/marsender/symfony-webhook/subscription',
				'commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/commits{/sha}',
				'git_commits_url' => 'https://api.github.com/repos/marsender/symfony-webhook/git/commits{/sha}',
				'comments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/comments{/number}',
				'issue_comment_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues/comments{/number}',
				'contents_url' => 'https://api.github.com/repos/marsender/symfony-webhook/contents/{+path}',
				'compare_url' => 'https://api.github.com/repos/marsender/symfony-webhook/compare/{base}...{head}',
				'merges_url' => 'https://api.github.com/repos/marsender/symfony-webhook/merges',
				'archive_url' => 'https://api.github.com/repos/marsender/symfony-webhook/{archive_format}{/ref}',
				'downloads_url' => 'https://api.github.com/repos/marsender/symfony-webhook/downloads',
				'issues_url' => 'https://api.github.com/repos/marsender/symfony-webhook/issues{/number}',
				'pulls_url' => 'https://api.github.com/repos/marsender/symfony-webhook/pulls{/number}',
				'milestones_url' => 'https://api.github.com/repos/marsender/symfony-webhook/milestones{/number}',
				'notifications_url' => 'https://api.github.com/repos/marsender/symfony-webhook/notifications{?since,all,participating}',
				'labels_url' => 'https://api.github.com/repos/marsender/symfony-webhook/labels{/name}',
				'releases_url' => 'https://api.github.com/repos/marsender/symfony-webhook/releases{/id}',
				'deployments_url' => 'https://api.github.com/repos/marsender/symfony-webhook/deployments',
				'created_at' => '2024-03-24T16:40:06Z',
				'updated_at' => '2024-03-24T16:59:34Z',
				'pushed_at' => '2024-03-26T06:31:02Z',
				'git_url' => 'git://github.com/marsender/symfony-webhook.git',
				'ssh_url' => 'git@github.com:marsender/symfony-webhook.git',
				'clone_url' => 'https://github.com/marsender/symfony-webhook.git',
				'svn_url' => 'https://github.com/marsender/symfony-webhook',
				'homepage' => null,
				'size' => 271,
				'stargazers_count' => 0,
				'watchers_count' => 0,
				'language' => 'PHP',
				'has_issues' => true,
				'has_projects' => true,
				'has_downloads' => true,
				'has_wiki' => false,
				'has_pages' => false,
				'has_discussions' => false,
				'forks_count' => 0,
				'mirror_url' => null,
				'archived' => false,
				'disabled' => false,
				'open_issues_count' => 1,
				'license' => null,
				'allow_forking' => true,
				'is_template' => false,
				'web_commit_signoff_required' => false,
				'topics' => [],
				'visibility' => 'private',
				'forks' => 0,
				'open_issues' => 1,
				'watchers' => 0,
				'default_branch' => 'main',
			],
			'sender' => [
				'login' => 'marsender',
				'id' => 279979,
				'node_id' => 'MDQ6VXNlcjI3OTk3OQ==',
				'avatar_url' => 'https://avatars.githubusercontent.com/u/279979?v=4',
				'gravatar_id' => '',
				'url' => 'https://api.github.com/users/marsender',
				'html_url' => 'https://github.com/marsender',
				'followers_url' => 'https://api.github.com/users/marsender/followers',
				'following_url' => 'https://api.github.com/users/marsender/following{/other_user}',
				'gists_url' => 'https://api.github.com/users/marsender/gists{/gist_id}',
				'starred_url' => 'https://api.github.com/users/marsender/starred{/owner}{/repo}',
				'subscriptions_url' => 'https://api.github.com/users/marsender/subscriptions',
				'organizations_url' => 'https://api.github.com/users/marsender/orgs',
				'repos_url' => 'https://api.github.com/users/marsender/repos',
				'events_url' => 'https://api.github.com/users/marsender/events{/privacy}',
				'received_events_url' => 'https://api.github.com/users/marsender/received_events',
				'type' => 'User',
				'site_admin' => false,
			],
		];
	}

	private function getPingPayload(): array
	{
		return json_decode('
    {
      "zen": "Keep it logically awesome.",
      "hook_id": 470086609,
      "hook": {
        "type": "Repository",
        "id": 470086609,
        "name": "web",
        "active": true,
        "events": [
          "issues"
        ],
        "config": {
          "content_type": "json",
          "insecure_ssl": "0",
          "url": "https://webhook.host/webhook/github"
        },
        "updated_at": "2024-04-01T21:27:42Z",
        "created_at": "2024-04-01T21:27:42Z",
        "url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609",
        "test_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/test",
        "ping_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/pings",
        "deliveries_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks/470086609/deliveries",
        "last_response": {
          "code": null,
          "status": "unused",
          "message": null
        }
      },
      "repository": {
        "id": 770981096,
        "node_id": "R_kgDOLfQ86A",
        "name": "symfony-assetmapper",
        "full_name": "marsender/symfony-assetmapper",
        "private": false,
        "owner": {
          "login": "marsender",
          "id": 279979,
          "node_id": "MDQ6VXNlcjI3OTk3OQ==",
          "avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/marsender",
          "html_url": "https://github.com/marsender",
          "followers_url": "https://api.github.com/users/marsender/followers",
          "following_url": "https://api.github.com/users/marsender/following{/other_user}",
          "gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
          "organizations_url": "https://api.github.com/users/marsender/orgs",
          "repos_url": "https://api.github.com/users/marsender/repos",
          "events_url": "https://api.github.com/users/marsender/events{/privacy}",
          "received_events_url": "https://api.github.com/users/marsender/received_events",
          "type": "User",
          "site_admin": false
        },
        "html_url": "https://github.com/marsender/symfony-assetmapper",
        "description": null,
        "fork": false,
        "url": "https://api.github.com/repos/marsender/symfony-assetmapper",
        "forks_url": "https://api.github.com/repos/marsender/symfony-assetmapper/forks",
        "keys_url": "https://api.github.com/repos/marsender/symfony-assetmapper/keys{/key_id}",
        "collaborators_url": "https://api.github.com/repos/marsender/symfony-assetmapper/collaborators{/collaborator}",
        "teams_url": "https://api.github.com/repos/marsender/symfony-assetmapper/teams",
        "hooks_url": "https://api.github.com/repos/marsender/symfony-assetmapper/hooks",
        "issue_events_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues/events{/number}",
        "events_url": "https://api.github.com/repos/marsender/symfony-assetmapper/events",
        "assignees_url": "https://api.github.com/repos/marsender/symfony-assetmapper/assignees{/user}",
        "branches_url": "https://api.github.com/repos/marsender/symfony-assetmapper/branches{/branch}",
        "tags_url": "https://api.github.com/repos/marsender/symfony-assetmapper/tags",
        "blobs_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/blobs{/sha}",
        "git_tags_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/tags{/sha}",
        "git_refs_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/refs{/sha}",
        "trees_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/trees{/sha}",
        "statuses_url": "https://api.github.com/repos/marsender/symfony-assetmapper/statuses/{sha}",
        "languages_url": "https://api.github.com/repos/marsender/symfony-assetmapper/languages",
        "stargazers_url": "https://api.github.com/repos/marsender/symfony-assetmapper/stargazers",
        "contributors_url": "https://api.github.com/repos/marsender/symfony-assetmapper/contributors",
        "subscribers_url": "https://api.github.com/repos/marsender/symfony-assetmapper/subscribers",
        "subscription_url": "https://api.github.com/repos/marsender/symfony-assetmapper/subscription",
        "commits_url": "https://api.github.com/repos/marsender/symfony-assetmapper/commits{/sha}",
        "git_commits_url": "https://api.github.com/repos/marsender/symfony-assetmapper/git/commits{/sha}",
        "comments_url": "https://api.github.com/repos/marsender/symfony-assetmapper/comments{/number}",
        "issue_comment_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues/comments{/number}",
        "contents_url": "https://api.github.com/repos/marsender/symfony-assetmapper/contents/{+path}",
        "compare_url": "https://api.github.com/repos/marsender/symfony-assetmapper/compare/{base}...{head}",
        "merges_url": "https://api.github.com/repos/marsender/symfony-assetmapper/merges",
        "archive_url": "https://api.github.com/repos/marsender/symfony-assetmapper/{archive_format}{/ref}",
        "downloads_url": "https://api.github.com/repos/marsender/symfony-assetmapper/downloads",
        "issues_url": "https://api.github.com/repos/marsender/symfony-assetmapper/issues{/number}",
        "pulls_url": "https://api.github.com/repos/marsender/symfony-assetmapper/pulls{/number}",
        "milestones_url": "https://api.github.com/repos/marsender/symfony-assetmapper/milestones{/number}",
        "notifications_url": "https://api.github.com/repos/marsender/symfony-assetmapper/notifications{?since,all,participating}",
        "labels_url": "https://api.github.com/repos/marsender/symfony-assetmapper/labels{/name}",
        "releases_url": "https://api.github.com/repos/marsender/symfony-assetmapper/releases{/id}",
        "deployments_url": "https://api.github.com/repos/marsender/symfony-assetmapper/deployments",
        "created_at": "2024-03-12T13:35:23Z",
        "updated_at": "2024-03-20T20:46:10Z",
        "pushed_at": "2024-03-29T17:24:02Z",
        "git_url": "git://github.com/marsender/symfony-assetmapper.git",
        "ssh_url": "git@github.com:marsender/symfony-assetmapper.git",
        "clone_url": "https://github.com/marsender/symfony-assetmapper.git",
        "svn_url": "https://github.com/marsender/symfony-assetmapper",
        "homepage": null,
        "size": 405,
        "stargazers_count": 1,
        "watchers_count": 1,
        "language": "PHP",
        "has_issues": true,
        "has_projects": true,
        "has_downloads": true,
        "has_wiki": false,
        "has_pages": false,
        "has_discussions": false,
        "forks_count": 0,
        "mirror_url": null,
        "archived": false,
        "disabled": false,
        "open_issues_count": 0,
        "license": null,
        "allow_forking": true,
        "is_template": false,
        "web_commit_signoff_required": false,
        "topics": [

        ],
        "visibility": "public",
        "forks": 0,
        "open_issues": 0,
        "watchers": 1,
        "default_branch": "main"
      },
      "sender": {
        "login": "marsender",
        "id": 279979,
        "node_id": "MDQ6VXNlcjI3OTk3OQ==",
        "avatar_url": "https://avatars.githubusercontent.com/u/279979?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/marsender",
        "html_url": "https://github.com/marsender",
        "followers_url": "https://api.github.com/users/marsender/followers",
        "following_url": "https://api.github.com/users/marsender/following{/other_user}",
        "gists_url": "https://api.github.com/users/marsender/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/marsender/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/marsender/subscriptions",
        "organizations_url": "https://api.github.com/users/marsender/orgs",
        "repos_url": "https://api.github.com/users/marsender/repos",
        "events_url": "https://api.github.com/users/marsender/events{/privacy}",
        "received_events_url": "https://api.github.com/users/marsender/received_events",
        "type": "User",
        "site_admin": false
      }
    }
		', true);
	}
}
