# see https://symfony.com/doc/current/routing.html
controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

webhook:
  resource: '@FrameworkBundle/Resources/config/routing/webhook.php'
  prefix: /webhook
