# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind: # defines the scalar arguments once and apply them to any service defined/created in this file
      #$adminEmail: '%env(ADMIN_EMAIL)%'
      #$cacheDir: '%kernel.cache_dir%'
      #$logDir: '%kernel.logs_dir%'
      $projectDir: '%kernel.project_dir%'
      $boardExportPath: '%env(BOARD_EXPORT_PATH)%'
      $mattermostApiUrl: '%env(MATTERMOST_API_URL)%'
      $mattermostAuthToken: '%env(MATTERMOST_AUTH_TOKEN)%'
      $mattermostLoginUser: '%env(MATTERMOST_LOGIN_USER)%'
      $mattermostLoginPassword: '%env(MATTERMOST_LOGIN_PASSWORD)%'
      $mattermostBoardApiUrl: '%env(MATTERMOST_BOARD_API_URL)%'
      $mattermostBoardConfig: '%env(MATTERMOST_BOARD_CONFIG)%'

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/'
    exclude:
      - '../src/DependencyInjection/'
      - '../src/Entity/'
      - '../src/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
